apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::640001687359:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::640001687359:role/eksctl-eksctl-demo-nodegroup-ng-b3-NodeInstanceRole-IxLrw1W9B71N
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-27T14:26:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1259"
  uid: a50a2c51-5a8d-426f-87dc-7e1ae723c8bd
